# COAP Î¢·þÎñ
spring:
  application:
    name: service-coap
  devtools:
    livereload:
      port: 35297
server:
  port: 5500

eureka:
  instance:
    hostname: service-coap1
  client:

    serviceUrl:
      defaultZone: http://localhost:4500/eureka/
