# Server Info
server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
# Spring
spring:
  application:
    name: service-coap
  data:
    #Mongodb
    mongodb:
      database: EASYLINKER
      host: localhost
      port: 27017

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    # password: root

# Coap Server
coap:
  server:
    hostname: localhost
    port: 5683
# V3
easylinkerV3:
  host: localhost
  port: 2500

# actuator
info:
  appname: coap-service
  author: wwhai
  blog-url: http://www.shinelinker.com
  version: '@project.version@'
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
