spring:
  application:
    name: service-coap
  data:
  #Mongodb
    mongodb:
      database: EASYLINKER
      host: localhost
      port: 27017
  #Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/v3?serverTimezone=UTC&tinyInt1isBit=false&useSSL=false
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8002

  tomcat:
    uri-encoding: UTF-8

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# Coap Server
coap:
  server:
    hostname: localhost
    port: 5683
# V3
easylinkerV3:
  host: localhost
  port: 2500

# actuator
info:
  appname: coap-service
  author: wwhai
  blog-url: http://www.shinelinker.com
  version: '@project.version@'
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
