# Server Info
server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
# Spring
spring:
  application:
    name: service-file
  data:
    #Mongodb
    mongodb:
      database: EASYLINKER
      host: localhost
      port: 27017

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    # password: root

