# Server Info
server:
  port: 8003
  tomcat:
    uri-encoding: UTF-8
# Spring
spring:
  application:
    name: service-mqtt
  data:
    #Mongodb
    mongodb:
      database: EASYLINKER
      host: localhost
      port: 27017
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    password: fourthpay-redis
# MQTT proxy client for easylinkerV3
proxy:
  mqtt:
    host: localhost
    port: 1883
    # Broker support:
    # Activemq 5.X
    # EMQX 3.X
    # Value:EMQ|AMQ
    broker: AMQ

